create table PRODUCT(
    ID BIGINT NOT NULL,
    NAME VARCHAR( 100 ) NOT NULL,
    PRIMARY KEY ( ID )
);

CREATE TABLE PRICES(
    PRICE_LIST BIGINT NOT NULL AUTO_INCREMENT,
    BRAND_ID TINYINT NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY TINYINT NOT NULL,
    PRICE NUMERIC( 9, 2 ) NOT NULL,
    CURR VARCHAR( 5 ),
    PRIMARY KEY ( PRICE_LIST ),
    CONSTRAINT FK_PRODUCT_ID_PRICES
    FOREIGN KEY ( PRODUCT_ID )
    REFERENCES PRODUCT( ID )
);

CREATE TABLE USERS(
    USER_ID VARCHAR( 50 ) NOT NULL,
    PASSWORD VARCHAR( 100 ) NOT NULL,
    ROLES VARCHAR( 100 ),
    SCOPES VARCHAR( 100 ),
    PRIMARY KEY ( USER_ID )
);